### ISSUE TITLE
[Merging 5.8.0] spits "Uncaught ReferenceError: tern is not defined"

### ISSUE THREAD

**Issue by hwshim** [webida/CodeMirror#64]
I tried to merge cm 5.8.0 but it fails for code-editor plugin.
(But It works for text-editor plugin.)

![image](https://cloud.githubusercontent.com/assets/7447396/11270371/c3b7cefc-8f01-11e5-90fc-08f56b7f9435.png)

**Comment by happibum** [comment]
Resolved in #65
